python train.py --device cpu --max-epochs 75 --seed 3407 \
                --use-log --log-interval 50 --use-tensorboard --save \
                --use-val --split-ratio 0.8 0.2 --val-interval 1 --num-workers 4 \
                --batch-size 4 \
                --transform-train zoo/transform_instances/complex.yaml \
                --transform-val zoo/transform_instances/none.yaml \
                --model mobilenet_v3_s --pretrained --norm-layer batchnorm --dropout 0.0 \
                --optimizer sgd --lr 1e-3 --momentum 0.95 --weight-decay 1e-4 --grad-clip 1. \
                --scheduler cosinelr --period 5 --period-mult 2 --min-lr 3e-5 \
                --criterion focalloss --focal-alpha 5 --focal-gamma 1.5 \
                --eval-loss --eval-acc \